networks:
  frontend:
    external: true
    name: reverse-proxy
  backend:
    driver: bridge

services:
  web:
    image: odoo:17.0
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
    environment:
    - HOST=${DB_HOST}
    - USER=${DB_USER}
    - PASSWORD=${DB_PASSWORD}
    networks:
     - frontend
     - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      # http
      - "traefik.http.routers.odoo.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.odoo.entrypoints=web"
      
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
     - backend

volumes:
  odoo-web-data:
  odoo-db-data:
