networks:
  frontend:
    external: true
    name: reverse-proxy
  backend:
    driver: bridge

services:
  odoo:
    image: odoo:17.0
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
    - HOST=${DB_HOST}
    - USER=${DB_USER}
    - PASSWORD=${DB_PASSWORD}
    networks:
     - frontend
     - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      # https
      - "traefik.http.routers.odoo.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.odoo.entrypoints=websecure"
      - "traefik.http.routers.odoo.tls=true"
      - "traefik.http.routers.odoo.tls.certresolver=letsencrypt"
  postgres:
    image: postgres:15
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
     - backend

volumes:
  odoo-web-data:
  odoo-db-data:
